spring:
  application:
    name: sc-eureka-server
server:
  port: 8669

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
  client:
    serviceUrl:
      defaultZone: http://localhost:8669/eureka/
---
spring:
  profiles: test

---
spring:
  profiles: alidev

---
spring:
  profiles: prod1
server:
  port: 8669
eureka:
  instance:
    hostname: peer1
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
  client:
    serviceUrl:
      defaultZone: http://peer2:8669/eureka/,http://peer3:8669/eureka/
---
spring:
  profiles: prod2
server:
  port: 8669
eureka:
  instance:
    hostname: peer2
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
  client:
    serviceUrl:
      defaultZone: http://peer1:8669/eureka/,http://peer3:8669/eureka/
---
spring:
  profiles: prod3
server:
  port: 8669
eureka:
  instance:
    hostname: peer3
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
  client:
    serviceUrl:
      defaultZone: http://peer1:8669/eureka/,http://peer2:8669/eureka/