server:
  port: 8669                    # 指定该Eureka实例的端口
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8669/eureka/

# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode
# 参考文档：http://my.oschina.net/buwei/blog/618756