spring:
  application:
    name: sc-eureka-server
server:
  port: 8669

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
  client:
    serviceUrl:
      defaultZone: http://localhost:8669/eureka/
    register-with-eureka: false
    fetch-registry: false
---
spring:
  profiles: test
---
spring:
  profiles: testbug
  server:
      port: 8669
  eureka:
    instance:
      prefer-ip-address: true
    server:
      enable-self-preservation: false
      eviction-interval-timer-in-ms: 2000
    client:
      serviceUrl:
        defaultZone: http://172.19.173.115:8669/eureka/
      registerWithEureka: false
      fetchRegistry: false
---
spring:
  profiles: dev
  server:
    port: 8669
  eureka:
    instance:
      prefer-ip-address: true
    server:
      enable-self-preservation: false
      eviction-interval-timer-in-ms: 2000
    client:
      serviceUrl:
        defaultZone: http://172.19.173.93:8669/eureka/
      registerWithEureka: false
      fetchRegistry: false
---
spring:
  profiles: prod1
server:
  port: 8669
eureka:
  instance:
    prefer-ip-address: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
  client:
    serviceUrl:
      defaultZone: http://192.168.2.228:8669/eureka/,http://192.168.2.225:8669/eureka/
---
spring:
  profiles: prod2
server:
  port: 8669
eureka:
  instance:
    prefer-ip-address: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
  client:
    serviceUrl:
      defaultZone: http://192.168.2.226:8669/eureka/,http://192.168.2.225:8669/eureka/
---
spring:
  profiles: prod3
server:
  port: 8669
eureka:
  instance:
    prefer-ip-address: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
  client:
    serviceUrl:
      defaultZone: http://192.168.2.226:8669/eureka/,http://192.168.2.228:8669/eureka/
---
spring:
  profiles: devfk2
server:
  port: 8669
eureka:
  instance:
    prefer-ip-address: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
  client:
    serviceUrl:
      defaultZone: http://192.168.2.90:8669/eureka/,http://192.168.2.99:8669/eureka/
---
spring:
  profiles: devfk1
server:
  port: 8669
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
  client:
    serviceUrl:
      defaultZone: http://192.168.2.99:8669/eureka/,http://192.168.2.90:8669/eureka/
---
