server:
  port: 8669                    # 指定该Eureka实例的端口
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8669/eureka/

---
spring:
  profiles: test

---
spring:
  profiles: alidev

---
spring:
  profiles: prod1
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8669/eureka/,http://peer3:8669/eureka/
---
spring:
  profiles: prod2
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8669/eureka/,http://peer3:8669/eureka/
---
spring:
  profiles: prod3
eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
      defaultZone: http://peer2:8669/eureka/,http://peer3:8669/eureka/