server:
  port: 9666
spring:
  application:
    name: sc-zipkin-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8669/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

---
spring:
  profiles: test
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8669/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

---
spring:
  profiles: prod
eureka:
  instance:
    prefer-ip-address: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8669/eureka/
