server:
  port: 8060

spring:
  application:
    name: yhyy-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8669/eureka/
  instance:
    prefer-ip-address: true

zuul:
  routes:
    ecej-service: /z/**

ribbon:
  ReadTimeout: 10000              #请求处理的超时时间
  ConnectTimeout: 10000           #ribbon请求连接的超时时间
  MaxAutoRetries: 3               #对当前实例的重试次数
  MaxAutoRetriesNextServer: 1    #对下个实例的重试次数

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000